#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Mako
Version  : 1.0.2
Release  : 14
URL      : https://pypi.python.org/packages/source/M/Mako/Mako-1.0.2.tar.gz
Source0  : https://pypi.python.org/packages/source/M/Mako/Mako-1.0.2.tar.gz
Summary  : A super-fast templating language that borrows the  best ideas from the existing templating languages.
Group    : Development/Tools
License  : MIT
Requires: Mako-bin
Requires: Mako-python
BuildRequires : MarkupSafe
BuildRequires : funcsigs
BuildRequires : nose
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python-mock
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six

%description
=========================
Mako Templates for Python
=========================
Mako is a template library written in Python. It provides a familiar, non-XML
syntax which compiles into Python modules for maximum performance. Mako's
syntax and API borrows from the best ideas of many others, including Django
templates, Cheetah, Myghty, and Genshi. Conceptually, Mako is an embedded
Python (i.e. Python Server Page) language, which refines the familiar ideas
of componentized layout and inheritance to produce one of the most
straightforward and flexible models available, while also maintaining close
ties to Python calling and scoping semantics.

%package bin
Summary: bin components for the Mako package.
Group: Binaries

%description bin
bin components for the Mako package.


%package python
Summary: python components for the Mako package.
Group: Default
Provides: mako-python

%description python
python components for the Mako package.


%prep
%setup -q -n Mako-1.0.2

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python2 setup.py test
%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}
python3 setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mako-render

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
